# Generated by Django 4.0.3 on 2022-03-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgSource', models.CharField(max_length=60)),
                ('text', models.CharField(max_length=60)),
            ],
        ),
    ]
